# Generated by Django 5.2.7 on 2026-03-16 11:22

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(choices=[('student', 'Student'), ('academic_supervisor', 'Academic Supervisor'), ('workplace_supervisor', 'Workplace Supervisor')], default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
        ),
    ]
