# Generated by Copilot on 2026-04-11

import uuid
from django.db import migrations, models
import django.db.models.deletion
import django.conf.settings


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('settings_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('log_reminders', models.BooleanField(default=True)),
                ('review_alerts', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=False)),
                ('profile_visible', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=False)),
                ('show_phone', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=django.conf.settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
