# Generated by Django 5.2.7 on 2026-05-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='login_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
