# Generated by Django 5.2.7 on 2026-06-06 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_institution_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'supervisor_type': 'academic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='accounts.supervisor'),
        ),
    ]
