# Generated by Django 5.2.7 on 2026-06-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_student_academic_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_supervisor',
        ),
    ]
