# Generated by Django 5.2.7 on 2026-03-14 22:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('metric_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('internships_completed', 'Internships Completed'), ('average_score', 'Average Score'), ('pending_reviews', 'Pending Reviews'), ('total_students', 'Total Students'), ('active_placements', 'Active Placements')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
