# Generated by Django 5.2.7 on 2026-05-05 07:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('log_review_pending', 'Log Review Pending'), ('submission_deadline', 'Submission Deadline'), ('evaluation_completed', 'Evaluation Completed'), ('placement_approved', 'Placement Approved'), ('placement_rejected', 'Placement Rejected'), ('feedback_added', 'Feedback Added'), ('log_submitted', 'Log Submitted'), ('system_health_update', 'System Health Update'), ('server_status_update', 'Server Status Update'), ('pending_updates', 'Pending Updates'), ('system_alert', 'System Alert'), ('new_company_added', 'New Company Added'), ('login_alert', 'Login Alert')], max_length=50),
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('login_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user_agent', models.TextField()),
                ('logged_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_in_at'],
                'indexes': [models.Index(fields=['user', '-logged_in_at'], name='notificatio_user_id_4712a4_idx')],
            },
        ),
    ]
