# Generated by Django 5.2.7 on 2026-05-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_notification_type_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
