# Generated by Django 5.2.7 on 2026-05-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_loginhistory_city_alter_loginhistory_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('log_review_pending', 'Log Review Pending'), ('submission_deadline', 'Submission Deadline'), ('evaluation_completed', 'Evaluation Completed'), ('placement_approved', 'Placement Approved'), ('placement_rejected', 'Placement Rejected'), ('placement_submitted', 'Placement Submitted'), ('placement_letter_deleted', 'Placement Letter Deleted'), ('feedback_added', 'Feedback Added'), ('log_submitted', 'Log Submitted'), ('system_health_update', 'System Health Update'), ('server_status_update', 'Server Status Update'), ('pending_updates', 'Pending Updates'), ('system_alert', 'System Alert'), ('new_company_added', 'New Company Added'), ('login_alert', 'Login Alert')], max_length=50),
        ),
    ]
