# Generated by Django 5.2.7 on 2026-03-14 22:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('criteria_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_date', models.DateField(default=django.utils.timezone.now)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('comments', models.TextField(blank=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supervisor')),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='placements.internshipplacement')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreBreakdown',
            fields=[
                ('score_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supervisor_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('academic_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('logbook_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='placements.internshipplacement')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('score_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationcriteria')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluation')),
            ],
            options={
                'unique_together': {('evaluation', 'criteria')},
            },
        ),
    ]
