# Generated by Django 5.2.7 on 2026-06-14 16:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0003_weeklylog_scheduled_submission_at_and_status'),
        ('placements', '0002_internshipplacement_is_submitted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='final_reports/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='placements.internshipplacement')),
            ],
        ),
    ]
