# Generated by Django 5.2.7 on 2026-03-14 22:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPlacement',
            fields=[
                ('placement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('position_title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('academic_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_placements', to='accounts.supervisor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('workplace_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace_placements', to='accounts.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('introduction_letter', 'Introduction Letter'), ('acceptance_letter', 'Acceptance Letter'), ('contract', 'Contract')], max_length=20)),
                ('file_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.internshipplacement')),
            ],
        ),
    ]
