# Generated by Django 5.2.7 on 2026-03-25 10:36

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDashboardMetric',
            fields=[
                ('metric_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for the metric')),
                ('metric_type', models.CharField(choices=[('internships_completed', 'Internships Completed'), ('average_score', 'Average Score'), ('pending_reviews', 'Pending Reviews'), ('total_students', 'Total Students'), ('active_placements', 'Active Placements')], help_text='Type of metric', max_length=50)),
                ('value', models.DecimalField(decimal_places=2, help_text='Current value of the metric', max_digits=10)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when this metric was calculated')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Record last update timestamp')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Dashboard Metric',
                'verbose_name_plural': 'historical Dashboard Metrics',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='dashboardmetric',
            options={'ordering': ['-calculated_at'], 'verbose_name': 'Dashboard Metric', 'verbose_name_plural': 'Dashboard Metrics'},
        ),
        migrations.AddField(
            model_name='dashboardmetric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Record creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboardmetric',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='calculated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when this metric was calculated'),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='metric_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the metric', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='metric_type',
            field=models.CharField(choices=[('internships_completed', 'Internships Completed'), ('average_score', 'Average Score'), ('pending_reviews', 'Pending Reviews'), ('total_students', 'Total Students'), ('active_placements', 'Active Placements')], help_text='Type of metric', max_length=50),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Current value of the metric', max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardmetric',
            unique_together={('metric_type', 'calculated_at')},
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['metric_type'], name='dashboards__metric__354ade_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['calculated_at'], name='dashboards__calcula_f7dedb_idx'),
        ),
        migrations.AddField(
            model_name='historicaldashboardmetric',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
